[tool.pyflow]
name = "casf"
py_version = "3.8"
# [[[fill version_sync()]]]
version = "2022.3.14"
# [[[end]]] (checksum: 3239a27d9a4b91f89023d7d20de106cd)
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
black = "^22.3.0"
coverage = "^6.4.1"
flake8 = "^4.0.1"
flake8-quotes = "^3.3.1"
hypothesis = "^6.47.5"
isort = "^5.10.1"
mypy = "^0.961"
pycodestyle = "^2.8.0"
pyflakes = "^2.4.0"
pygments = "^2.12.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.1"
pytest-sugar = "^0.9.4"
pytest-toolbox = "^0.4"
types-jmespath = "^0.10.3"
types-setuptools = "^57.4.18"
