[tool.pyflow]
name = "casf"
py_version = "3.8"
# [[[fill version_sync()]]]
version = "2022.3.12"
# [[[end]]] (checksum: 745e84f28c64e43a101dbb5731b86b5d)
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
jmespath = "^0.10.0"
jsonschema = "^4.4.0"
langcodes = "^3.3.0"
lazr.uri = "^1.0.6"
orjson = "^3.6.7"
pydantic = "^1.9.0"
scooby = "^0.5.12"
typer = "^0.4.0"
